name = "FemtoCompiler"
uuid = "92d42091-2d14-46a9-a897-febf9702e17e"
version = "0.1.0"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]

[deps]
JuliaCore = "4dea8d58-8095-4b52-84ae-e93c853b8479"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"

[sources]
JuliaCore = {path = "JuliaCore"}

[extensions]
CompilerExt = "JuliaCore"

[syntax]
julia_version = "1.14"

[compat]
julia = "1.11"
JuliaCore = "0.1"
Jive = "0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
