name = "FemtoCompiler"
uuid = "92d42091-2d14-46a9-a897-febf9702e17e"
version = "0.1.0"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]

[compat]
julia = "1.12"
Jive = "0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"

[targets]
test = ["Test", "Jive"]
